---
title: "demo3"
author: "Ville Laitinen"
date: "21 3 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
```

# Monte Carlo integration  importance sampling
## 1 a)

```{r}
x <- runif(10000, 0, 1)

exp(2*x) %>% mean
```

## 1 b)

```{r}
x <- runif(1000, 0, 2)

(2 - 0)*exp(2*x) %>% mean
```


# Importance sampling

## 2
```{r}
x <- runif(1000, 0, 1)


inv_G <- function(x) -1*log(1 - x*(exp(1) - 1)/exp(1))
g <- function(x) (exp(-x+1))/(exp(1)-1)
f <- function(x) exp(-x^2)
p <- function(x) dunif(x, 0, 1)

# weight
w <- function(x) p(x)/g(x)



weighted_mc <- function(n = 1000) {
  X <- inv_G(runif(n, 0, 1))
  X <- X[X<=1]
  Y <- w(X)*f(X)
  c(mean = mean(Y), var = var(Y))
}

normal_mc <- function(n = 1000) {
  x <- runif(n, 0, 1)
  c(mean = mean(f(x)), var = var(f(x)))
}

print("Importance weighing mean and variance")
weighted_mc()

print("No importance weighing mean and variance")
normal_mc()


```


* Compare variance as a function of n

```{r}

comparison_df <- lapply(1000*c(1, 2, 5, 10, 20, 50, 100), function(n) {
  rbind(
    c(n, weighted_mc(n)),
    c(n, normal_mc(n))
  ) %>% as.data.frame() %>% 
    cbind(c("yes", "no"))
  
}) %>%
  do.call(rbind, .) %>%
  set_colnames(c("n", "mean", "var", "weight"))

p_var <- comparison_df %>%
  ggplot(aes(x = n, y = var, color = weight)) +
  geom_line() +
  labs(title = "Variance")

p_mean <- comparison_df %>%
  ggplot(aes(x = n, y = mean, color = weight)) +
  geom_line() +
  labs(title = "Mean")

print(p_var)
print(p_mean)

```


## 3. 

* Importance sampling with Uniform[0, 3] as the importance function (= non importance sampling?)

```{r}

x <- runif(10000, 0, 3)

# f(x) = x
(3 - 0)*x %>% mean

# f(x) = x^2
(3 - 0)*x^2 %>% mean

```


```{r}
AADD <- function(X) {
    
  Y <- c()  
  for(i in 1:length(X)) {
    x <- X[i]
          if(x < 0 | x > 3) {
        y <- 0
      } else if(x < 1) {
        y <-  .5*x
      } else if (x > 2) {
        y <-  .5 - .5*(x - 2)
      } else if(x < 2 & 1 < x) {
        y <- .5
      }
    Y <- c(Y, y)
  }

  Y
}
inv_AADD_CDF <- function(x) {
  
  if(x < 0 | 1 < x) {
    stop("x not in [0, 1]")
  }
  
  if(x < .25) {
    y <- 2*sqrt(x)
  } else if(x < .75) {
    y <- 2*x + .5
  } else {
    y <- 3 - 2*sqrt(1-x)
  }
  
  return(y)
}



weighted_mc <- function(n = 1000, a, b, f, q, inv_cdf_q) {
  
  x <- runif(n)
  X <- sapply(x, inv_cdf_q)
  
  w <- function(x) dunif(x, a, b)/q(x)
  Y <- (b - a)*w(X)*f(X)
  
  c(mean = mean(Y), var = var(Y))
}



normal_mc <- function(n = 1000, a, b, func) {
  x <- runif(n, a, b)
  c(mean = (b-a)*mean(func(x)), var = var(func(x)))
}



# f(x) = x
weighted_mc(10000, 0, 3,
            f = function(x) x,
            q = function(x) AADD(x),
            inv_cdf_q = function(x) inv_AADD_CDF(x))

# f(x) = x^2
weighted_mc(10000, 0, 3,
            f = function(x) x^2,
            q = function(x) AADD(x),
            inv_cdf_q = function(x) inv_AADD_CDF(x))
```


```{r}

compare_estimates <- lapply(1000*c(1, 2, 5, 10, 20, 50, 100), function(n) {
  
  x <- runif(n, 0, 1)
  
  x_mc <- normal_mc(n, 0, 3, function(x) x)
  x2_mc <- normal_mc(n, 0, 3, function(x) x^2)
  
  
  x_aadd <- weighted_mc(10000, 0, 3,
                               f = function(x) x,
                               q = function(x) AADD(x),
                               inv_cdf_q = function(x) inv_AADD_CDF(x))
  x2_aadd <-  weighted_mc(10000, 0, 3,
                               f = function(x) x^2,
                               q = function(x) AADD(x),
                               inv_cdf_q = function(x) inv_AADD_CDF(x))
  
  df <- rbind(x_mc, x2_mc, x_aadd, x2_aadd) %>% 
    as.data.frame() %>% 
    cbind(func = c("x", "x2", "x", "x2"),
          method = c("normal", "normal", "weight", "weigth"),
          n = rep(n, 4))
    
    
  
  
  df
  
}) %>% 
  do.call(rbind, .) 



compare_estimates %>% 
  filter(func == "x") %>% 
  ggplot(aes(x = n, y = var, color = method)) +
  geom_line() +
  labs(title = "x variance")


compare_estimates %>% 
  filter(func == "x2") %>% 
  ggplot(aes(x = n, y = var, color = method)) +
  geom_line() +
  labs(title = "x2 variance")


compare_estimates %>% 
  filter(func == "x") %>% 
  ggplot(aes(x = n, y = mean, color = method)) +
  geom_line() +
  labs(title = "x mean")

compare_estimates %>% 
  filter(func == "x2") %>% 
  ggplot(aes(x = n, y = mean, color = method)) +
  geom_line()+
  labs(title = "x2 mean")

```



************************************************************
************************************************************
************************************************************
************************************************************


## DUMP
```{r}


weighted_mc <- function(n = 1000, f) {
  
  x <- runif(n)
  X <- sapply(x, inv_AADD_CDF)
  
  w <- function(x) dunif(x, 0, 3)/AADD(x)
  Y <- 3*w(X)*f(X)
  
  mean(Y)
}


```

